image: docker:latest
# services:
#   - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - before_build
  - build

before-build:
  stage: before_build
  image: docker:dind
  script:
    - echo "build OK.";

build:
  stage: build
  image: docker:dind
  script:
    - apk update && apk add curl
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# TODO: Find a way to make this code below works somehow
#     - chmod +x /usr/local/bin/docker-compose
#     - /usr/local/bin/docker-compose up -d

# test:
#   stage: build
#   script: 
#     - docker ps
    