<?php
// <!-- This will store a password as well as salt 
// to prevent the attack done by the users. -->
// Note: User must set this $pass_pepper uniquely
// to prevent a further attack done by a malicious user.
// salt is also be created for every user.

error_reporting(E_ALL ^ E_WARNING ^ E_NOTICE);

// TODO: Enable random pepper generation when 
// a server is created.
$pass_pepper="_____pepper_input_____";
$time_sheet_manager_pass="_____time_sheet_pass_____";


// TODO: Session needs to be generated by SHA3
session_name('employee_password_man');
session_start();

// print_r($_COOKIE);
// Prevent session id hijacking.
if ($_SERVER['REMOTE_ADDR'] != $_SESSION['ipaddress'])
{
  session_unset();
  session_destroy();
}

if ($_SERVER['HTTP_USER_AGENT'] != $_SESSION['useragent'])
{
  session_unset();
  session_destroy();
}

// TODO: Create a PDO-based command that inputs 
// a user's account info & password into database.
echo "Success."


?>