<?php

// Unset already started session to create a value.


// TODO: Session needs to be generated by SHA3
session_name('employee_password_man');
session_start([
  'cookie_lifetime' =>600,
]);
session_regenerate_id(true);

// unset($_SESSION);
// $_SESSION=array();

// if ($_SERVER['REMOTE_ADDR'] != $_SESSION['ipaddress'])
// {
//   session_unset();
//   session_destroy();
// }

// if ($_SERVER['HTTP_USER_AGENT'] != $_SESSION['useragent'])
// {
//   session_unset();
//   session_destroy();
// }

// print_r($_COOKIE);
# Insert ip & user agent to see if 
# a user is the same user he / she access to this website 
# with a specified cookie (Very strict security measure.).
$_SESSION['ipaddress']=$_SERVER['REMOTE_ADDR'];
$_SESSION['useragent']=$_SERVER['HTTP_USER_AGENT'];
echo $_SESSION['ipaddress'];
// echo session_id();
// setcookie ( "employee_session" , session_id(), $path="/");

require_once("/var/www/html/plugin/strip_malicious_character.php");

$password_format="/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d]{8,}$/";
$illegal_password_format="/[^A-Za-z0-9]+/";

// Check password format before input as it may 
// be altered by malicious attempts of javascript code modifications.
if( !preg_match($password_format,$_POST["employeePassword"]) || 
    preg_match($illegal_password_format,$_POST["employeePassword"])){
      echo "Unknown password error.";
      exit(1);
    }

// Set user's session info that is already input by a user.
$_SESSION["user_info"]=$_POST;


print_r($_SESSION);
?>


<!-- TODO: Enable strict session id check. -->
<!-- Load css files. -->
<link href='/css/bootstrap.min.css' rel='stylesheet'>
<link href='/css/index.css' rel='stylesheet'>


<div class="container align-items-center" id="formReview">
  <h1 style="text-align: center">Account Registration Review</h1>
  <div class="Review-window">
    First  Name <br>
    <?php echo stripMaliciousChar($_POST["employeeFirstName"]) ?><br><br>
    Middle Name <br>
    <?php echo stripMaliciousChar($_POST["employeeMiddleName"]) ?><br><br>
    Last Name<br>
     <?php echo stripMaliciousChar($_POST["employeeLastName"]) ?><br><br>
    Address<br>
     <?php echo stripMaliciousChar($_POST["employeeAddress"]) ?><br><br>
    Phone Number<br>
     <?php echo stripMaliciousChar($_POST["employeePhoneNumber"]) ?><br><br>
    Email<br>
    <?php echo stripMaliciousChar($_POST["employeeEmail"]) ?><br><br>
    Password: ****
  </div>
  <div>
  <div  class="d-flex justify-content-center">
    <div class="col-auto mx-3">
      <!-- Proceed to the output. -->
      <button class="btn btn-primary" onclick="window.location='/employee/employee_account_confirmation_complete.php'">
        Confirm 
      </button>
    </div>    
    <div class="col-auto mx-3">
    <!-- Go back to the previous page. -->
      <button class="btn btn-primary" onclick="window.location='/employee/employee_account_registration.php'">
      Back 
      </button>
    </div>
  </div>
</div>
